version: '3.8'

services:
  # JWT Validator Service
  jwt-validator:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - OTEL_SERVICE_NAME=jwt-validator
      - OTEL_RESOURCE_ATTRIBUTES=service.name=jwt-validator,deployment.environment=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_PROPAGATORS=tracecontext,baggage
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://jaeger:9411
      - SPRINGDOC_SWAGGER_UI_PATH=/
      - SPRINGDOC_API_DOCS_PATH=/v3/api-docs
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    networks:
      - monitoring-network
    depends_on:
      - jaeger
      - prometheus

  # Jaeger 
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "16686:16686" # UI
      - "14250:14250" # Model
      - "14268:14268" # Jaeger HTTP
      - "9411:9411"   # Zipkin compatible endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - monitoring-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - monitoring-network

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  grafana-storage:
